2018-10-25 20:01:02,092 ERROR: Exception on /create_location [GET] [in C:\Users\Sonya\labs_205\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\Sonya\labs_205\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Sonya\labs_205\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Sonya\labs_205\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Sonya\labs_205\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\Sonya\labs_205\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Sonya\labs_205\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Sonya\labs_205\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Sonya\Documents\Fall2018\labs_205\app\routes.py", line 200, in create_location
    return render_template('create_location.html',  title='Sign In', form=form)
NameError: name 'form' is not defined
